Page({
  data: {
    "title": "美食路线",
    "scale": 12,
    "layerStyle": 1,
    "latitude": 29.263606679591735,
    "longitude": 117.23635760729644,
    "originalLatitude": 0,
    "originalLongitude": 0,
    "markers": [
      {
        "id": 1709877667395,
        "createdAt": "2023-11-29T11:58:12.859+08:00",
        "updatedAt": "2024-01-31T18:31:58.669+08:00",
        "poiID": 10,
        "feature": "夜宴",
        "thumbnail": "https://jingheyijia-cop.oss-cn-chengdu.aliyuncs.com/upload/1701246542897_景德镇早餐打卡系列我又回来了～_1_夏花的七月_来自小红书网页版.webp",
        "address": "景德镇市珠山区中华北路148号",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 1,
        "weight": 300,
        "openHours": "07:00-23:00",
        "mapVisible": 2,
        "lat": 29.300465,
        "lon": 117.204036,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "景德镇人最喜欢的特色美食-饺子粑，30多年的熬浆工艺制作的饺子粑，晶莹剔透的皮包含着萝卜丝，韭菜等，冬天来一份配合一碗暖心鸡蛋肉饼汤。",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 27,
        "collectionCount": 0,
        "storeType": 2,
        "dialogTitle": "三角井粑店",
        "storeID": 1123,
        "latitude": 29.300465,
        "longitude": 117.204036,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "三角井粑店",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667397,
        "createdAt": "2023-11-29T11:50:04.617+08:00",
        "updatedAt": "2023-12-21T14:54:00.443+08:00",
        "poiID": 8,
        "feature": "夜宴",
        "thumbnail": "https://jingheyijia-cop.oss-cn-chengdu.aliyuncs.com/upload/1701246806786_景德镇City walk-小毛老面汤包_1_kiki💗_来自小红书网页版.webp",
        "address": "景德镇市珠山区中山南路256号",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 2,
        "weight": 300,
        "openHours": "早上7:00-凌晨3:00",
        "mapVisible": 2,
        "lat": 29.286061,
        "lon": 117.208252,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "三十多年的瓷都老店，瓷都人最喜欢的冷粉，拌面还有各种汤包，一口咬开满满的汤汁溢出来。",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 33,
        "collectionCount": 0,
        "storeType": 2,
        "dialogTitle": "小毛老面汤包",
        "storeID": 1122,
        "latitude": 29.286061,
        "longitude": 117.208252,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "小毛老面汤包",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667398,
        "createdAt": "2023-11-29T11:43:33.475+08:00",
        "updatedAt": "2023-12-21T14:54:00.443+08:00",
        "poiID": 8,
        "feature": "夜宴",
        "thumbnail": "https://jingheyijia-cop.oss-cn-chengdu.aliyuncs.com/upload/1701229409247_fzjbd.png",
        "address": "景德镇市珠山区中华南路176号",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 2,
        "weight": 500,
        "openHours": "10:00 - 22:00",
        "mapVisible": 2,
        "lat": 29.289627,
        "lon": 117.210182,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "李玉刚对这家的煎饼赞不绝口。很香很油很润的煎饼，每个来到这里的人都说好吃。喜欢碳水的来到景德镇千万不要错过哟。",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 36,
        "collectionCount": 0,
        "storeType": 2,
        "dialogTitle": "冯氏煎饼店",
        "storeID": 1121,
        "latitude": 29.289627,
        "longitude": 117.210182,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "冯氏煎饼店",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667399,
        "createdAt": "2023-08-01T22:26:23.297+08:00",
        "updatedAt": "2024-01-31T18:52:33.29+08:00",
        "poiID": 8,
        "feature": "夜宴",
        "thumbnail": "https://static.cop.jingheyijia.com/dev/yzsmap/photo/抚州弄油条包麻糍.jpg",
        "address": "抚州弄5号",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 1,
        "weight": 5,
        "openHours": "7:30-20:30",
        "mapVisible": 2,
        "lat": 29.285483,
        "lon": 117.213956,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "一口酥脆的油条加上香甜软糯的麻糍，这就是记忆里童年的味道！来到景德镇绝对不能少了这个油条包麻糍！",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 0,
        "collectionCount": 0,
        "storeType": 2,
        "dialogTitle": "抚州弄油条摊",
        "storeID": 1174,
        "latitude": 29.285483,
        "longitude": 117.213956,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "抚州弄油条摊",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667400,
        "createdAt": "2023-11-29T14:26:39.049+08:00",
        "updatedAt": "2023-12-21T14:54:00.443+08:00",
        "poiID": 10,
        "feature": "夜宴",
        "thumbnail": "https://jingheyijia-cop.oss-cn-chengdu.aliyuncs.com/upload/1701241358927_微信图片_20231129150225.jpg",
        "address": "珠山区中山南路景德镇市第六小学旁",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 1,
        "weight": 254,
        "openHours": "06:00 - 17:00",
        "mapVisible": 2,
        "lat": 29.289348,
        "lon": 117.207145,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "江西每个地方都有自己的粉，那么属于景德镇就一定是冷粉了，QQ弹弹的粗粉配合各种开胃的小菜一起搅拌，真是又辣又过瘾。这家店要注意位置可能不好找哟，可以多问问周围的居民。",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 19,
        "collectionCount": 0,
        "storeType": 2,
        "dialogTitle": "金金冷粉",
        "storeID": 1133,
        "latitude": 29.289348,
        "longitude": 117.207145,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "金金冷粉",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667401,
        "createdAt": "2023-11-29T14:16:15.828+08:00",
        "updatedAt": "2023-12-21T14:54:00.443+08:00",
        "poiID": 10,
        "feature": "夜宴",
        "thumbnail": "https://jingheyijia-cop.oss-cn-chengdu.aliyuncs.com/upload/1701246017269_xypd.webp",
        "address": "珠山区沿江东路110号",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 1,
        "weight": 200,
        "openHours": "7:00 - 11:00，14:00 - 17:00",
        "mapVisible": 2,
        "lat": 29.288463,
        "lon": 117.204457,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "晶莹剔透的饺子粑，韭菜和萝卜馅整整齐齐的排列在蒸笼里，配上一碗紫菜肉饼汤不由的让人胃口大开。",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 25,
        "collectionCount": 0,
        "storeType": 2,
        "dialogTitle": "鑫益粑店",
        "storeID": 1130,
        "latitude": 29.288463,
        "longitude": 117.204457,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "鑫益粑店",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667402,
        "createdAt": "2023-11-29T14:40:35.187+08:00",
        "updatedAt": "2023-12-21T14:54:00.443+08:00",
        "poiID": 10,
        "feature": "夜宴",
        "thumbnail": "https://jingheyijia-cop.oss-cn-chengdu.aliyuncs.com/upload/1701244684263_lzjj3.webp",
        "address": "中山南路六小旁",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 2,
        "weight": 10,
        "openHours": "07:00-17:00",
        "mapVisible": 2,
        "lat": 29.290156,
        "lon": 117.206967,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "外焦里嫩的煎饺配合特有的蘸酱，一口下去肉汁十足，再来一碗汤，又是元气满满的一天。",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 16,
        "collectionCount": 0,
        "storeType": 2,
        "dialogTitle": "老张煎饺",
        "storeID": 1134,
        "latitude": 29.290156,
        "longitude": 117.206967,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "老张煎饺",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667403,
        "createdAt": "2023-11-29T14:03:19.12+08:00",
        "updatedAt": "2023-12-21T14:54:00.443+08:00",
        "poiID": 10,
        "feature": "夜宴",
        "thumbnail": "https://jingheyijia-cop.oss-cn-chengdu.aliyuncs.com/upload/1701246345815_wjngf.webp",
        "address": "珠山区抚州弄6-36号13号",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 1,
        "weight": 300,
        "openHours": "10:00 - 22:00",
        "mapVisible": 2,
        "lat": 29.2924,
        "lon": 117.210113,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "张记烧饼",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 14,
        "collectionCount": 0,
        "storeType": 2,
        "dialogTitle": "吴记牛骨粉",
        "storeID": 1127,
        "latitude": 29.2924,
        "longitude": 117.210113,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "吴记牛骨粉",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667404,
        "createdAt": "2023-11-29T13:55:35.702+08:00",
        "updatedAt": "2023-12-21T14:54:00.443+08:00",
        "poiID": 10,
        "feature": "夜宴",
        "thumbnail": "https://jingheyijia-cop.oss-cn-chengdu.aliyuncs.com/upload/1701244107123_zjsb1.jpg",
        "address": "珠山区戴家上弄49号",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 1,
        "weight": 300,
        "openHours": "10:00 - 22:00",
        "mapVisible": 2,
        "lat": 29.292823,
        "lon": 117.210237,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "一口下去嘎嘣脆，涂上酱料更美味！焦香酥脆的乌腌菜烧饼配合秘制的酱料，让烧饼充满灵魂，还有里面是白糖的甜烧饼哟！就是要小心烫嘴。",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 2,
        "collectionCount": 0,
        "storeType": 2,
        "dialogTitle": "张记烧饼",
        "storeID": 1125,
        "latitude": 29.292823,
        "longitude": 117.210237,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "张记烧饼",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667405,
        "createdAt": "2023-11-29T14:21:53.402+08:00",
        "updatedAt": "2023-12-21T14:54:00.443+08:00",
        "poiID": 10,
        "feature": "夜宴",
        "thumbnail": "https://jingheyijia-cop.oss-cn-chengdu.aliyuncs.com/upload/1701244891942_ffsz.webp",
        "address": "珠山区抚州弄1号",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 1,
        "weight": 300,
        "openHours": "8:00 - 22:00",
        "mapVisible": 2,
        "lat": 29.292764,
        "lon": 117.209976,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "寒冷的冬天点上一碗水煮，暖暖的汤底配合麻辣的味道，瞬间身上暖和了起来。",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 26,
        "collectionCount": 0,
        "storeType": 2,
        "dialogTitle": "芳芳水煮",
        "storeID": 1132,
        "latitude": 29.292764,
        "longitude": 117.209976,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "芳芳水煮",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667406,
        "createdAt": "2023-08-01T22:26:23.297+08:00",
        "updatedAt": "2024-02-01T15:59:51.304+08:00",
        "poiID": 4,
        "feature": "夜宴",
        "thumbnail": "https://jingheyijia-cop.oss-cn-chengdu.aliyuncs.com/upload/1702607712833_北安碱水粑1.jpg.png",
        "address": "陶阳南路1号17--16",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 1,
        "weight": 1,
        "openHours": "10:00-22:00",
        "mapVisible": 2,
        "lat": 29.289299,
        "lon": 117.250042,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "瓷都特有的美食“碱水粑”，刨的薄薄的碱水粑配合鸡蛋、大蒜、雪里蕻等蔬菜一起翻炒，一碗嚼劲十足的碱水粑就出来。",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 0,
        "collectionCount": 1,
        "storeType": 2,
        "dialogTitle": "北安碱水粑",
        "storeID": 374,
        "latitude": 29.289299,
        "longitude": 117.250042,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "北安碱水粑",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667407,
        "createdAt": "2023-12-15T11:19:37.687+08:00",
        "updatedAt": "2024-03-07T17:44:00.837+08:00",
        "poiID": 2,
        "feature": "夜宴",
        "thumbnail": "https://jingheyijia-cop.oss-cn-chengdu.aliyuncs.com/upload/1702609223306_老宇宙清汤排挡1.jpg.png",
        "address": "景德镇市珠山区陶玉南路山水瑞园B2栋2号店",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 2,
        "weight": 80,
        "openHours": "9:00-22:00",
        "mapVisible": 2,
        "lat": 29.289527,
        "lon": 117.237576,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "皮薄香滑的清汤（馄饨）配上猪油渣鲜美可口，再来上一份炒粉，美美的一餐就解决了。",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 25,
        "collectionCount": 1,
        "storeType": 2,
        "dialogTitle": "老宇宙清汤排档",
        "storeID": 1169,
        "latitude": 29.289527,
        "longitude": 117.237576,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "老宇宙清汤排档",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667408,
        "createdAt": "2023-11-29T13:53:50.946+08:00",
        "updatedAt": "2023-12-21T14:54:00.443+08:00",
        "poiID": 10,
        "feature": "夜宴",
        "thumbnail": "https://jingheyijia-cop.oss-cn-chengdu.aliyuncs.com/upload/1701246472886_袁记面馆_3_紫青_来自小红书网页版.webp",
        "address": "风景路珠山派出所对面",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 2,
        "weight": 10,
        "openHours": "06:00-12:30",
        "mapVisible": 2,
        "lat": 29.298549,
        "lon": 117.206487,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "寒冷的冬天，一碗分量十足的盖浇面再加上一个荷包蛋，一口下去补充一天的能量。",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 16,
        "collectionCount": 0,
        "storeType": 2,
        "dialogTitle": "袁记面馆",
        "storeID": 1124,
        "latitude": 29.298549,
        "longitude": 117.206487,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "袁记面馆",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667409,
        "createdAt": "2023-12-21T14:34:27.065+08:00",
        "updatedAt": "2024-01-08T15:00:41.066+08:00",
        "poiID": 8,
        "feature": "夜宴",
        "thumbnail": "https://jingheyijia-cop.oss-cn-chengdu.aliyuncs.com/upload/1703140457089_细哥排档.png",
        "address": "景德镇市珠山区浙江路中夏金都城7-8号细哥排挡私房菜",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 2,
        "weight": 500,
        "openHours": "16:00-01:00",
        "mapVisible": 2,
        "lat": 29.285133,
        "lon": 117.209583,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "景德镇人从小吃到大的炒排粉，充满锅气的排粉再加上红绿点缀，让人食欲大开。",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 17,
        "collectionCount": 0,
        "storeType": 2,
        "dialogTitle": "细哥排档",
        "storeID": 1171,
        "latitude": 29.285133,
        "longitude": 117.209583,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "细哥排档",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      },
      {
        "id": 1709877667410,
        "createdAt": "2023-08-01T22:26:23.297+08:00",
        "updatedAt": "2023-08-01T22:26:23.297+08:00",
        "poiID": 8,
        "feature": "夜宴",
        "thumbnail": "https://static.cop.jingheyijia.com/dev/yzsmap/photo/陶姐冷粉.jpg",
        "address": "怡翠园113号",
        "mobile": "",
        "description": "",
        "active": 2,
        "recommend": 1,
        "weight": 5,
        "openHours": "10:00-22:00",
        "mapVisible": 2,
        "lat": 29.285483,
        "lon": 117.213956,
        "isLike": false,
        "isCollection": false,
        "pin": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "mediaType": 0,
        "l12": 1,
        "l13": 1,
        "l14": 1,
        "l15": 1,
        "l16": 1,
        "l17": 1,
        "l18": 1,
        "strategy": "景德镇独有的冷粉，让喜爱吃辣的人心神向往，怕辣的朋友也可以点上一碗绿豆汤解解辣。",
        "distance": 0,
        "recommendReason": "",
        "likeCount": 0,
        "collectionCount": 0,
        "storeType": 2,
        "dialogTitle": "陶姐冷粉",
        "storeID": 249,
        "latitude": 29.285483,
        "longitude": 117.213956,
        "iconPath": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic1.png",
        "pinActive": "https://static.cop.jingheyijia.com/wxapp-map2/image/ic_scenic_active1.png",
        "width": 40,
        "height": 40,
        "zIndex": 999,
        "callout": {
          "content": "陶姐冷粉",
          "color": "#FFFFFF",
          "borderWidth": "0px",
          "fontSize": "12px",
          "borderRadius": "10px",
          "bgColor": "#4b70fd",
          "padding": "6px",
          "display": "ALWAYS",
          "textAlign": "center"
        }
      }
    ],
    "polyline": [],
   
    "enable3d": false,
    "showCompass": false,
    "enableOverlooking": false,
    "enableZoom": true,
    "enableScroll": true,
    "enableRotate": false,
    "enableSatellite": false,
    "enableTraffic": false,
    "showLocation": false,
    "dialogTitle": "美食路线",
    "route": {},
    "routePoiStore": {},
    "distances": 0,
    "latlngs": {
      "latitude": "29.304301",
      "longitude": "117.272075"
    },
    "isShowParking": false,
    "isShowCheckin": false,
    "isShowMarkerInfo": false,
    "markerInfo": {},
    "activeMode": 0,
    "modeLeft": 0,

    "routeID": "4",
    "userScale": 0,

  },

  onload() {

  },
  onShow() {

  },
  update() {
    console.log('upadate')
    this.setData({
      markers: this.data.markers
    })
  }
})